locals {
  colors = {
    alice_blue             = "F0F8FF"
    antique_white          = "FAEBD7"
    aqua                   = "00FFFF"
    aquamarine             = "7FFFD4"
    azure                  = "F0FFFF"
    beige                  = "F5F5DC"
    bisque                 = "FFE4C4"
    black                  = "000000"
    blanched_almond        = "FFEBCD"
    blue                   = "0000FF"
    blue_violet            = "8A2BE2"
    brown                  = "A52A2A"
    burlywood              = "DEB887"
    cadet_blue             = "5F9EA0"
    chartreuse             = "7FFF00"
    chocolate              = "D2691E"
    coral                  = "FF7F50"
    cornflower_blue        = "6495ED"
    cornsilk               = "FFF8DC"
    crimson                = "DC143C"
    cyan                   = "00FFFF"
    dark_blue              = "00008B"
    dark_cyan              = "008B8B"
    dark_goldenrod         = "B8860B"
    dark_gray              = "A9A9A9"
    dark_green             = "006400"
    dark_khaki             = "BDB76B"
    dark_magenta           = "8B008B"
    dark_olive_green       = "556B2F"
    dark_orange            = "FF8C00"
    dark_orchid            = "9932CC"
    dark_red               = "8B0000"
    dark_salmon            = "E9967A"
    dark_sea_green         = "8FBC8F"
    dark_slate_blue        = "483D8B"
    dark_slate_gray        = "2F4F4F"
    dark_turquoise         = "00CED1"
    dark_violet            = "9400D3"
    deep_pink              = "FF1493"
    deep_sky_blue          = "00BFFF"
    dim_gray               = "696969"
    dodger_blue            = "1E90FF"
    fire_brick             = "B22222"
    floral_white           = "FFFAF0"
    forest_green           = "228B22"
    fuchsia                = "FF00FF"
    gainsboro              = "DCDCDC"
    ghost_white            = "F8F8FF"
    gold                   = "FFD700"
    goldenrod              = "DAA520"
    gray                   = "808080"
    green                  = "008000"
    green_yellow           = "ADFF2F"
    honeydew               = "F0FFF0"
    hot_pink               = "FF69B4"
    indian_red             = "CD5C5C"
    indigo                 = "4B0082"
    ivory                  = "FFFFF0"
    khaki                  = "F0E68C"
    lavender               = "E6E6FA"
    lavender_blush         = "FFF0F5"
    lawn_green             = "7CFC00"
    lemon_chiffon          = "FFFACD"
    light_blue             = "ADD8E6"
    light_coral            = "F08080"
    light_cyan             = "E0FFFF"
    light_goldenrod_yellow = "FAFAD2"
    light_gray             = "D3D3D3"
    light_green            = "90EE90"
    light_pink             = "FFB6C1"
    light_salmon           = "FFA07A"
    light_sea_green        = "20B2AA"
    light_sky_blue         = "87CEFA"
    light_slate_gray       = "778899"
    light_steel_blue       = "B0C4DE"
    light_yellow           = "FFFFE0"
    lime                   = "00FF00"
    lime_green             = "32CD32"
    linen                  = "FAF0E6"
    magenta                = "FF00FF"
    maroon                 = "800000"
    medium_aquamarine      = "66CDAA"
    medium_blue            = "0000CD"
    medium_orchid          = "BA55D3"
    medium_purple          = "9370DB"
    medium_sea_green       = "3CB371"
    medium_slate_blue      = "7B68EE"
    medium_spring_green    = "00FA9A"
    medium_turquoise       = "48D1CC"
    medium_violet_red      = "C71585"
    midnight_blue          = "191970"
    mint_cream             = "F5FFFA"
    misty_rose             = "FFE4E1"
    moccasin               = "FFE4B5"
    navajo_white           = "FFDEAD"
    navy                   = "000080"
    old_lace               = "FDF5E6"
    olive                  = "808000"
    olive_drab             = "6B8E23"
    orange                 = "FFA500"
    orange_red             = "FF4500"
    orchid                 = "DA70D6"
    pale_goldenrod         = "EEE8AA"
    pale_green             = "98FB98"
    pale_turquoise         = "AFEEEE"
    pale_violet_red        = "DB7093"
    papaya_whip            = "FFEFD5"
    peachpuff              = "FFDAB9"
    peru                   = "CD853F"
    pink                   = "FFC0CB"
    plum                   = "DDA0DD"
    powder_blue            = "B0E0E6"
    purple                 = "800080"
    red                    = "FF0000"
    rosy_brown             = "BC8F8F"
    royal_blue             = "4169E1"
    saddle_brown           = "8B4513"
    salmon                 = "FA8072"
    sandy_brown            = "F4A460"
    sea_green              = "2E8B57"
    seashell               = "FFF5EE"
    sienna                 = "A0522D"
    silver                 = "C0C0C0"
    sky_blue               = "87CEEB"
    slate_blue             = "6A5ACD"
    slate_gray             = "708090"
    snow                   = "FFFAFA"
    spring_green           = "00FF7F"
    steel_blue             = "4682B4"
    tan                    = "D2B48C"
    teal                   = "008080"
    thistle                = "D8BFD8"
    tomato                 = "FF6347"
    turquoise              = "40E0D0"
    violet                 = "EE82EE"
    wheat                  = "F5DEB3"
    white                  = "FFFFFF"
    white_smoke            = "F5F5F5"
    yellow                 = "FFFF00"
    yellow_green           = "9ACD32"
  }
}

variable "name" {
  description = "Firewall Category name."
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z0-9 _.:\\'-]{0,64}$", var.name))
    error_message = "Allowed characters: `a`-`z`, `A`-`Z`, `0`-`9`, ` `, `_`, `.`, `:`, `'`, `-`. Maximum characters: 64."
  }
}

variable "auto" {
  description = "If set, category will be removed when unused."
  type        = bool
  default     = false
}

variable "color" {
  description = "Pick a color to use"
  type        = string
  default     = "000000" #black

  validation {
    condition = alltrue([
      try(contains(["alice-blue", "antique-white", "aqua", "aquamarine", "azure", "beige", "bisque", "black", "blanched-almond", "blue", "blue-violet", "brown", "burlywood", "cadet-blue", "chartreuse", "chocolate", "coral", "cornflower-blue", "cornsilk", "crimson", "cyan", "dark-blue", "dark-cyan", "dark-goldenrod", "dark-gray", "dark-green", "dark-khaki", "dark-magenta", "dark-olive-green", "dark-orange", "dark-orchid", "dark-red", "dark-salmon", "dark-sea-green", "dark-slate-blue", "dark-slate-gray", "dark-turquoise", "dark-violet", "deep-pink", "deep-sky-blue", "dim-gray", "dodger-blue", "fire-brick", "floral-white", "forest-green", "fuchsia", "gainsboro", "ghost-white", "gold", "goldenrod", "gray", "green", "green-yellow", "honeydew", "hot-pink", "indian-red", "indigo", "ivory", "khaki", "lavender", "lavender-blush", "lawn-green", "lemon-chiffon", "light-blue", "light-coral", "light-cyan", "light-goldenrod-yellow", "light-gray", "light-green", "light-pink", "light-salmon", "light-sea-green", "light-sky-blue", "light-slate-gray", "light-steel-blue", "light-yellow", "lime", "lime-green", "linen", "magenta", "maroon", "medium-aquamarine", "medium-blue", "medium-orchid", "medium-purple", "medium-sea-green", "medium-slate-blue", "medium-spring-green", "medium-turquoise", "medium-violet-red", "midnight-blue", "mint-cream", "misty-rose", "moccasin", "navajo-white", "navy", "old-lace", "olive", "olive-drab", "orange", "orange-red", "orchid", "pale-goldenrod", "pale-green", "pale-turquoise", "pale-violet-red", "papaya-whip", "peachpuff", "peru", "pink", "plum", "powder-blue", "purple", "red", "rosy-brown", "royal-blue", "saddle-brown", "salmon", "sandy-brown", "sea-green", "seashell", "sienna", "silver", "sky-blue", "slate-blue", "slate-gray", "snow", "spring-green", "steel-blue", "tan", "teal", "thistle", "tomato", "turquoise", "violet", "wheat", "white", "white-smoke", "yellow", "yellow-green"], var.color), false) || can(regex("^[a-fA-F0-9]{6}$", var.color))
    ])
    error_message = "Allowed values: `alice-blue`, `antique-white`, `aqua`, `aquamarine`, `azure`, `beige`, `bisque`, `black`, `blanched-almond`, `blue`, `blue-violet`, `brown`, `burlywood`, `cadet-blue`, `chartreuse`, `chocolate`, `coral`, `cornflower-blue`, `cornsilk`, `crimson`, `cyan`, `dark-blue`, `dark-cyan`, `dark-goldenrod`, `dark-gray`, `dark-green`, `dark-khaki`, `dark-magenta`, `dark-olive-green`, `dark-orange`, `dark-orchid`, `dark-red`, `dark-salmon`, `dark-sea-green`, `dark-slate-blue`, `dark-slate-gray`, `dark-turquoise`, `dark-violet`, `deep-pink`, `deep-sky-blue`, `dim-gray`, `dodger-blue`, `fire-brick`, `floral-white`, `forest-green`, `fuchsia`, `gainsboro`, `ghost-white`, `gold`, `goldenrod`, `gray`, `green`, `green-yellow`, `honeydew`, `hot-pink`, `indian-red`, `indigo`, `ivory`, `khaki`, `lavender`, `lavender-blush`, `lawn-green`, `lemon-chiffon`, `light-blue`, `light-coral`, `light-cyan`, `light-goldenrod-yellow`, `light-gray`, `light-green`, `light-pink`, `light-salmon`, `light-sea-green`, `light-sky-blue`, `light-slate-gray`, `light-steel-blue`, `light-yellow`, `lime`, `lime-green`, `linen`, `magenta`, `maroon`, `medium-aquamarine`, `medium-blue`, `medium-orchid`, `medium-purple`, `medium-sea-green`, `medium-slate-blue`, `medium-spring-green`, `medium-turquoise`, `medium-violet-red`, `midnight-blue`, `mint-cream`, `misty-rose`, `moccasin`, `navajo-white`, `navy`, `old-lace`, `olive`, `olive-drab`, `orange`, `orange-red`, `orchid`, `pale-goldenrod`, `pale-green`, `pale-turquoise`, `pale-violet-red`, `papaya-whip`, `peachpuff`, `peru`, `pink`, `plum`, `powder-blue`, `purple`, `red`, `rosy-brown`, `royal-blue`, `saddle-brown`, `salmon`, `sandy-brown`, `sea-green`, `seashell`, `sienna`, `silver`, `sky-blue`, `slate-blue`, `slate-gray`, `snow`, `spring-green`, `steel-blue`, `tan`, `teal`, `thistle`, `tomato`, `turquoise`, `violet`, `wheat`, `white`, `white-smoke`, `yellow`, `yellow-green` or Hex Code without `#`."
  }
}